name: Build and Push Production

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Atualizado para versão mais recente LTS
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Deploy to production branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: production # Branch que a Hostinger vai puxar
          FOLDER: dist # Pasta que contém o build a ser enviado
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Deploy do Disk Gás: ({sha}) {msg}"
